name: Test CI
on:
  pull_request:
    types:
      - opened
    branches:
      - 'action_types/**'
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:
  push:
    branches:
      - action_types
    paths-ignore: 
      - '.github/workflows/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup workflow
        uses: actions/checkout@v4
      # - name: Install NodeJs
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy project
        run:  echo "Deploying"
      - name: Show github context
        run: echo "${{toJSON(github)}}"



    

    
