name: Website Deployment
on:
  push:
    branches:
      - control-workflow
jobs:
  dependencies:
    uses: ./.github/workflows/reusable.yml

  lint:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v4
        with:
          name: dependencies
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Restore dependencies
        run: |
          cp -r node_modules ./node_modules
          cp package.json ./package.json
          cp package-lock.json ./package-lock.json

      # - name: Get code
      #   uses: actions/checkout@v4
      # - name: Cache dependencies
      #   id: cache
      #   uses: actions/cache@v4
      #   with:
      #     path: node_modules
      #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci
      - name: Lint code
        run: npm run lint

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      # - name: Get code
      #   uses: actions/checkout@v4
      # - name: Cache dependencies
      #   id: cache
      #   uses: actions/cache@v4
      #   with:
      #     path: node_modules
      #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci
      - name: Test code
        # continue-on-error: true
        id: test-code
        run: |
          npm run test
      # - name: Check Test Results
      #   run: |
      #     echo "Outcome: ${{ steps.test-code.outcome }}"
      #     echo "Conclusion: ${{ steps.test-code.conclusion }}"
      - name: Upload test report
        if: failure() && steps.test-code.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # - name: Get code
      #   uses: actions/checkout@v4
      # - name: Cache dependencies
      #   id: cache
      #   uses: actions/cache@v4
      #   with:
      #     path: node_modules
      #     key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  
  report:
    if: failure()
    needs: [lint, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong..."
          echo "${{ toJSON(github) }}"
